name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version: '22'

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - run: vp install
      - run: vp check
      - run: vp test
      - run: vp pack

      - name: Publish to NPM
        run: |
          VERSION=$(node -p "require('./package.json').version")
          if [[ $VERSION == *"-"* ]]; then
            TAG="beta"
          else
            TAG="latest"
          fi
          pnpm publish --tag $TAG --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
